# FILE: foundry.toml
[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"
gas_reports = ["*"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[doc]
out = "docs"
title = "GreenShare Zircuit Contracts"

[etherscan]
zircuit_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.testnet.zircuit.com/api" }

[rpc_endpoints]
zircuit_testnet = "https://zircuit1-testnet.p2pify.com/"
zircuit_mainnet = "https://zircuit1-mainnet.p2pify.com/"